export default [
  {
    id: 1,
    title: "Pulp fiction",
    director: "Quentin Tarantino",
    runTime: "2h 34min",
    wonOscar: true,
    summary:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    genre: ["crime"],
    rating: 8.9,
    year: 1994,
    poster: "./movie photos/pulpFiction.jpg",
    trailerId: "tGpTpVyI_OQ",
    isFavorite: true,
    reviews: [],
  },
  {
    id: 2,
    title: "Heat",
    director: "Michael Mann",
    runTime: "2h 50min",
    wonOscar: false,
    summary:
      "A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.",
    cast: ["Al Pacino", "Robert De Niro", "Val Kilmer"],
    genre: ["action"],
    rating: 8.3,
    poster: "./movie photos/heat.jpg",
    trailerId: "14oNcFxiVaQ",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 3,
    title: "Law Abiding Citizen",
    director: "F. Gary Gray",
    runTime: "1h 49min",
    wonOscar: false,
    summary:
      "A frustrated man decides to take justice into his own hands after a plea bargain sets one of his family's killers free.",
    cast: ["Gerard Butler", "Jamie Foxx", "Leslie Bibb"],
    genre: ["crime"],
    rating: 7.4,
    poster: "./movie photos/LAW.jpg",
    trailerId: "LX6kVRsdXW4",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 4,
    title: "Troy",
    director: "Wolfgang Petersen",
    runTime: "2h 43min",
    wonOscar: false,
    summary:
      "An adaptation of Homer's great epic, the film follows the assault on Troy by the united Greek forces and chronicles the fates of the men involved.",
    cast: ["Brad Pitt", "Eric Bana", "Orlando Bloom"],
    genre: ["drama"],
    rating: 7.3,
    poster: "./movie photos/troy.jpg",
    trailerId: "znTLzRJimeY",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 5,
    title: "Mystic River",
    director: "Mystic River",
    runTime: "2h 18min",
    wonOscar: true,
    summary:
      "The lives of three men who were childhood friends are shattered when one of them has a family tragedy.",
    cast: ["Tim Robbins", "Sean Penn", "Kevin Bacon"],
    genre: ["drama"],
    rating: 7.9,
    poster: "./movie photos/mystic.jpg",
    trailerId: "W7NktJhrRYQ",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 6,
    title: "Ocean's Eleven",
    director: "Steven Soderbergh",
    runTime: "1h 56min",
    wonOscar: false,
    summary:
      "Danny Ocean and his ten accomplices plan to rob three Las Vegas casinos simultaneously.",
    cast: ["George Clooney", "Brad Pitt", "Julia Roberts"],
    genre: ["crime"],
    rating: 7.7,
    poster: "./movie photos/oceans.jpg",
    trailerId: "imm6OR605UI",
    isFavorite: false,
    reviews: ["funny", "great movie"],
  },
  {
    id: 7,
    title: "The Godfather",
    director: "Francis Ford Coppola",
    runTime: "2h 55min",
    wonOscar: true,
    summary:
      "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    genre: ["crime"],
    rating: 9.2,
    poster: "./movie photos/godfather.jpg",
    trailerId: "UaVTIH8mujA",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 8,
    title: "300",
    director: "Zack Snyder",
    runTime: "1h 57min",
    wonOscar: false,
    summary:
      "King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.",
    cast: ["Gerard Butler", "Lena Headey", "David Wenham"],
    genre: ["action"],
    rating: 7.6,
    poster: "./movie photos/300.jpg",
    trailerId: "UrIbxk7idYA",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 9,
    title: "Goodfellas",
    director: "Martin Scorsese",
    runTime: "2h 25min",
    wonOscar: true,
    summary:
      "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
    cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
    genre: ["crime"],
    rating: 8.7,
    poster: "./movie photos/goodfellas.jpg",
    trailerId: "2ilzidi_J8Q",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 10,
    title: "Wedding Crashers",
    director: "David Dobkin",
    runTime: "1h 59min",
    wonOscar: false,
    summary:
      "John Beckwith and Jeremy Grey, a pair of committed womanizers who sneak into weddings to take advantage of the romantic tinge in the air, find themselves at odds with one another when John meets and falls for Claire Cleary.",
    cast: ["Owen Wilson", "Vince Vaughn", "Rachel McAdams"],
    genre: ["comedy"],
    rating: 7,
    poster: "./movie photos/wedding.jpg",
    trailerId: "wKahFEgeRg8",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 11,
    title: "Olympus Has Fallen",
    director: "Antoine Fuqua",
    runTime: "1h 59min",
    wonOscar: false,
    summary:
      "Secret Service agent Mike Banning finds himself trapped inside the White House in the wake of a terrorist attack and works with national security to rescue the President from his kidnappers.",
    cast: ["Gerard Butler", "Aaron Eckhart", "Morgan Freeman"],
    genre: ["action"],
    rating: 6.5,
    poster: "./movie photos/olympus.jpg",
    trailerId: "ar-IaAx7s8k",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 12,
    title: "Dumb and Dumber",
    director: "Peter Farrelly",
    runTime: "1h 47min",
    wonOscar: false,
    summary:
      "After a woman leaves a briefcase at the airport terminal, a dumb limo driver and his dumber friend set out on a hilarious cross-country road trip to Aspen to return it.",
    cast: ["Jim Carrey", "Jeff Daniels", "Lauren Holly"],
    genre: ["comedy"],
    rating: 7.3,
    poster: "./movie photos/dumb.jpg",
    trailerId: "l13yPhimE3o",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 13,
    title: "The Hangover",
    director: "Todd Phillips",
    runTime: "1h 40min",
    wonOscar: false,
    summary:
      "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.",
    cast: ["Zach Galifianakis", "Bradley Cooper", "Justin Bartha"],
    genre: ["comedy"],
    rating: 7.7,
    poster: "./movie photos/hangover.jpg",
    trailerId: "tcdUhdOlz9M",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 14,
    title: "National Security",
    director: "Dennis Dugan",
    runTime: "1h 28min",
    wonOscar: false,
    summary:
      "Two mismatched security guards are thrown together to bust a smuggling operation.",
    cast: ["Martin Lawrence", "Steve Zahn", "Colm Feore"],
    genre: ["comedy"],
    rating: 5.6,
    poster: "./movie photos/NS.jpg",
    trailerId: "SgstaR60zNk",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 15,
    title: "Training Day",
    director: "Antoine Fuqua",
    runTime: "2h 2min",
    wonOscar: true,
    summary:
      "A rookie cop spends his first day as a Los Angeles narcotics officer with a rogue detective who isn't what he appears to be.",
    cast: ["Denzel Washington", "Ethan Hawke", "Scott Glenn"],
    genre: ["action"],
    rating: 7.7,
    poster: "./movie photos/TD.jpg",
    trailerId: "DXPJqRtkDP0",
    isFavorite: false,
    reviews: [],
  },
  {
    id: 16,
    title: "The Green Mile",
    director: "Frank Darabont",
    runTime: "3h 9min",
    wonOscar: false,
    summary:
      "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
    cast: ["Tom Hanks", "Michael Clarke Duncan", "David Morse"],
    genre: ["drama"],
    rating: 8.6,
    poster: "./movie photos/mile.jpg",
    trailerId: "Ki4haFrqSrw",
    isFavorite: false,
    reviews: [],
  },
];
